version: '3.8'

services:
  backend:
    build: ./back
    ports:
      - "5000:5000"
    env_file:
      - ./back/.env
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./back:/app
      - /app/node_modules

  frontend:
    build: ./front
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

networks:
  app-network:

volumes:
  mongodb-data: