version: '3.8'

services:
  backend:
    image: mehdirps/chatbot-mejusaem-back:latest
    build: ./back
    ports:
      - "5000:5000"
    env_file:
      - ./back/.env
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - ./back:/app
      - /app/node_modules

  frontend:
    image: mehdirps/chatbot-mejusaem-front:latest
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=3000
      - HOST=0.0.0.0     
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

networks:
  app-network:

volumes:
  mongodb-data: